swagger: '2.0'
info:
  version: 0.2.0
  title: Status API
  description: An API used to monitor status of various subscribed services
host: 'localhost:8080'
basePath: /
tags:
  - name: services
    description: Everything about services
  - name: downed
    description: Everything about downed services
  - name: maintenance
    description: Everything about services undegoing maintenance
schemes:
  - http
paths:
  /services:
    get:
      tags:
        - services
      summary: get the list of all subscribed services
      description: get the list of all subscribed services
      operationId: getServices
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
    post:
      tags:
        - services
      summary: add a new service to the pool
      description: add a service
      operationId: addService
      consumes:
        - application/json
      parameters:
        - name: Service
          in: body
          required: true
          schema:
            $ref: '#/definitions/Service'
      responses:
        '201':
          description: created
          schema:
            type: object
  '/services/{serviceID}':
    get:
      tags:
        - services
      summary: Get the status of the selected service
      description: ''
      operationId: getOneService
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the service to get.
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
    patch:
      tags:
        - services
      summary: modify a subscribed service
      description: ''
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the service to patch.
      responses:
        '200':
          description: OK
    delete:
      tags:
        - services
      summary: Remove a subscribed service from the pool
      description: ''
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the service to delete.
      responses:
        '200':
          description: OK
  /downed:
    get:
      tags:
        - downed
      description: get the list of all subscribed services
      operationId: getDown
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
    post:
      tags:
        - downed
      summary: Add a downed service to the list
      description: ''
      responses:
        '200':
          description: OK
  '/downed/{serviceID}':
    delete:
      tags:
        - downed
      summary: remove a service from the downed services list
      description: ''
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the downed service to delete.
      responses:
        '200':
          description: OK
  /maintenance:
    get:
      tags:
        - maintenance
      summary: Get the list of services undergoing maintenance
      description: ''
      responses:
        '200':
          description: OK
    post:
      tags:
        - maintenance
      summary: Add a service to the maintenance list
      description: ''
      responses:
        '200':
          description: OK
  '/maintenance/{serviceID}':
    delete:
      tags:
        - maintenance
      summary: Delete a service from the maintenance list
      description: ''
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the maintenance to delete.
      responses:
        '200':
          description: OK
definitions:
  Service:
    type: object
    properties:
      kind:
        type: string
      colour:
        type: string
      size:
        type: string
