swagger: '2.0'
info:
  version: 0.2.0
  title: Status API
  description: An API used to monitor status of various subscribed services
host: 'localhost:8080'
basePath: /
tags:
  - name: services
    description: Everything about services
  - name: downed
    description: Everything about downed services
  - name: maintenance
    description: Everything about services undegoing maintenance
schemes:
  - http
paths:
  /services:
    get:
      tags:
        - services
      summary: get the list of all subscribed services
      description: get the list of all subscribed services
      operationId: getServices
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
    post:
      tags:
        - services
      summary: add a new service to the pool
      description: add a service
      operationId: addService
      consumes:
        - application/json
      parameters:
        - name: Service(s)
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
      responses:
        '201':
          description: created
        '400':
          description: Bad request
    put:
      tags:
        - services
      summary: modify a subscribed service
      description: ''
      parameters:
        - in: body
          name: Service(s)
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID
        '403':
          description: Forbidden
        '404':
          description: Service not found
  '/services/{serviceID}':
    get:
      tags:
        - services
      summary: Get the status of the selected service
      description: ''
      operationId: getOneService
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the service to get.
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Service'
        '400':
          description: Invalid ID
        '404':
          description: Service not found
    patch:
      tags:
        - services
      summary: Set the maintenance status for a service
      description: ''
      parameters:
        - in: path
          name: serviceID
          required: true
          description: Numeric ID of the service to patch.
          type: integer
        - in: header
          name: state
          type: integer
          required: true
          description: The new state of the service
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID
        '404':
          description: Service not found
    delete:
      tags:
        - services
      summary: Remove a subscribed service from the pool
      description: ''
      parameters:
        - in: path
          name: serviceID
          type: integer
          required: true
          description: Numeric ID of the service to delete.
      responses:
        '200':
          description: OK
        '400':
          description: Invalid ID
        '404':
          description: Service not found
  /downed:
    get:
      tags:
        - downed
      description: get the list of all subscribed services
      operationId: getDown
      produces:
        - application/json
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
  /maintenance:
    get:
      tags:
        - maintenance
      summary: Get the list of services undergoing maintenance
      description: ''
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Service'
definitions:
  Service:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      statusAddress:
        type: string
      description:
        type: string
      state:
        type: integer
      contact:
        type: string
