version: '2'
services:
  database:
    build: mysql/
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: phpmyadmin/
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - database:db
  springboot:
    build: microservice-status
    ports:
     - "8080:8080"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://database/status
