version: '2'
services:
  database:
    image: pestakit/status-db
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  springboot:
    image: pestakit/status
    ports:
     - "8080:8080"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://database/status
